NepalJobPortal/Models/OrganizationViewModel.cs
namespace NepalJobPortal.Models
{
    public class OrganizationViewModel : CommonViewModel
    {
        public int? OrgId { get; set; }
        public string OrgName { get; set; }
        public string OrgAddress { get; set; }
        public string OrgContact { get; set; }
        public string OrgEmail { get; set; }
        public string? OrgImage { get; set; }

        public List<OrganizationViewModel> OrganizationList { get; set;}

        public OrganizationViewModel()
        {
            OrganizationList = new List<OrganizationViewModel>();
        }

    }
}

NepalJobPortal/Controllers/OrganizationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NepalJobPortal.Data;
using NepalJobPortal.EntityModel;
using NepalJobPortal.Migrations;
using NepalJobPortal.Models;
using NepalJobPortal.Utilities;
using System.Security.Claims;
using static System.Net.Mime.MediaTypeNames;

namespace NepalJobPortal.Controllers
{
    [Authorize]
    public class OrganizationController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;
        private readonly UserManager<ApplicationIdentityUser> _userManager;
        public OrganizationController(ApplicationDbContext applicationDbContext, UserManager<ApplicationIdentityUser> userManager)
        {
            _applicationDbContext = applicationDbContext;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            OrganizationViewModel model = new OrganizationViewModel();
            model.OrganizationList = (from i in _applicationDbContext.Organization
                                      where i.IsDeleted == false
                                      select new OrganizationViewModel
                                      {
                                          OrgId = i.OrgId,
                                          OrgName = i.OrgName,
                                          OrgAddress = i.OrgAddress,
                                          OrgContact = i.OrgContact,
                                          OrgEmail = i.OrgEmail,
                                          OrgImage = i.OrgImage,
                                      }).ToList();
            return View(model);
        }

        public IActionResult Create()
        {
            //ViewBag.OrganizationList = _applicationDbContext.Organization
            //                            .Where(x => x.IsDeleted == false)
            //                            .ToList();

            return View();
        }

        //[HttpPost]
        //public IActionResult Create(OrganizationViewModel model)
        //{
        //    Organization org = new Organization();
        //    org.OrgName = model.OrgName;
        //    org.OrgAddress = model.OrgAddress;
        //    org.OrgEmail = model.OrgEmail;
        //    org.OrgContact = model.OrgContact;
        //    org.Status = true;
        //    org.CreatedBy = 1;
        //    org.CreatedDate = DateTime.Now;
        //    _applicationDbContext.Entry(org).State = EntityState.Added;
        //    _applicationDbContext.SaveChanges();

        //    ApplicationIdentityUser user = new ApplicationIdentityUser();
        //    user.Email = model.OrgEmail;
        //    user.OrgId = org.OrgId;
        //    //_userStore.SetUserNameAsync(user, Input.Email, CancellationToken.None);
        //    var result = _userManager.CreateAsync(user, $"{model.OrgName}@123");
        //    if (result.IsCompletedSuccessfully)
        //    {
        //        _userManager.AddToRoleAsync(user, "Vendor");
        //    }
        //        return RedirectToAction("Index");
        //}

        [HttpPost]
        public IActionResult Create(OrganizationViewModel model, IFormFile? file)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }
            //ViewBag.OrganizationList = _applicationDbContext.Organization
            //                            .Where(x => x.IsDeleted == false)
            //                            .ToList();
            if (file != null)
            {
                var GuidId = Guid.NewGuid().ToString();
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Files");
                if (!Directory.Exists(path))
                    Directory.CreateDirectory(path);
                string fileName = GuidId + file.FileName;
                string fileNameWithPath = Path.Combine(path, fileName);
                using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                {
                    file.CopyTo(stream);
                }
                model.OrgImage = "/Files/" + GuidId + file.FileName;
            }

            int currentloginOrgId = CommonUtilities.GetCurrentUserId(_applicationDbContext, User.FindFirstValue(ClaimTypes.NameIdentifier));
            using (var transaction = _applicationDbContext.Database.BeginTransaction())
            {
                try
                {
                    Organization org = new Organization
                    {
                        OrgName = model.OrgName,
                        OrgAddress = model.OrgAddress,
                        OrgEmail = model.OrgEmail,
                        OrgContact = model.OrgContact,
                        OrgImage = model.OrgImage,
                        Status = true,
                        CreatedBy = currentloginOrgId,
                        CreatedDate = DateTime.Now
                    };
                    _applicationDbContext.Entry(org).State = EntityState.Added;
                    _applicationDbContext.SaveChanges();

                    ApplicationIdentityUser user = new ApplicationIdentityUser
                    {
                        UserName = model.OrgEmail,
                        Email = model.OrgEmail,
                        OrgId = org.OrgId,
                        EmailConfirmed = true,
                    };
                    var result = _userManager.CreateAsync(user, $"{model.OrgName}@Vo123").Result;
                    if (result.Succeeded)
                    {
                        _userManager.AddToRoleAsync(user, "Vendor").Wait();
                        transaction.Commit();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        transaction.Rollback();
                        ModelState.AddModelError(string.Empty, "Failed to create user.");
                    }
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                    ModelState.AddModelError(string.Empty, "An error occurred while creating the organization.");
                }
            }
            return View(model); 
        }

        public IActionResult Edit(int id)
        {
            OrganizationViewModel model = new OrganizationViewModel();
            if (id > 0)
            {
                var org = _applicationDbContext.Organization.Where(x=>x.OrgId == id).FirstOrDefault();  
                if(org != null)
                {
                    model.OrgId = org.OrgId;
                    model.OrgName = org.OrgName;
                    model.OrgAddress = org.OrgAddress;
                    model.OrgEmail = org.OrgEmail;
                    model.OrgContact = org.OrgContact;
                    model.OrgImage = org.OrgImage;
                }
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(OrganizationViewModel model, IFormFile? file)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            int currentloginOrgId = CommonUtilities.GetCurrentUserId(_applicationDbContext, User.FindFirstValue(ClaimTypes.NameIdentifier));

            if (file != null)
            {
                var GuidId = Guid.NewGuid().ToString();
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Files");
                if (!Directory.Exists(path))
                    Directory.CreateDirectory(path);
                string fileName = GuidId + file.FileName;
                string fileNameWithPath = Path.Combine(path, fileName);
                using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                {
                    file.CopyTo(stream);
                }
                model.OrgImage = "/Files/" + GuidId + file.FileName;
            }
            Organization org = new Organization();
            org.OrgId = model.OrgId??0;
            org.OrgName = model.OrgName;
            org.OrgAddress = model.OrgAddress;
            org.OrgEmail = model.OrgEmail;
            org.OrgContact = model.OrgContact;
            org.OrgImage = model.OrgImage;
            org.Status = true;
            org.UpdatedBy = currentloginOrgId;
            org.UpdatedDate = DateTime.Now;
            _applicationDbContext.Entry(org).State = EntityState.Modified;
            _applicationDbContext.Entry(org).Property(x => x.CreatedBy).IsModified = false;
            _applicationDbContext.Entry(org).Property(x => x.CreatedDate).IsModified = false;
            if(model.OrgImage == null)
            {
                _applicationDbContext.Entry(org).Property(x => x.OrgImage).IsModified = false;
            }
            _applicationDbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            if (id > 0)
            {
                int currentloginOrgId = CommonUtilities.GetCurrentUserId(_applicationDbContext, User.FindFirstValue(ClaimTypes.NameIdentifier));
                var org = _applicationDbContext.Organization.Where(x => x.OrgId == id).FirstOrDefault();
                if (org != null)
                {
                    org.DeletedBy = currentloginOrgId;
                    org.DeletedDate = DateTime.Now;
                    org.IsDeleted = true;
                    _applicationDbContext.Entry(org).State = EntityState.Modified;
                    _applicationDbContext.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }
    }
}

NepalJobPortal/Views/Organization/Create.cshtml
@model NepalJobPortal.Models.OrganizationViewModel

@using Microsoft.Extensions.DependencyInjection
@* @inject IServiceProvider ServiceProvider
@using NepalJobPortal.Utilities; *@

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

    // Func<IEnumerable<SelectListItem>> getOrgList = () => CommonUtilities.GetOrganizationList(ServiceProvider);
}

<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Organization</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">Organization</a></li>
                            <li><a href="@Url.Action("Index","Organization")">List</a></li>
                            <li class="active">Create</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-9">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="card">
                <div class="card-header"><strong>Create Organization</strong></div>
                <div class="card-body card-block">

                    @* <div class="form-group">
                        <label>Select Organization</label>
                        <select asp-for="OrgId" class="form-control"
                                asp-items="@(new SelectList(ViewBag.OrganizationList,"OrgId","Name"))">
                        </select>
                        <span asp-validation-for="OrgName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label>Select</label>
                        <select asp-for="OrgId" name="selectedCategoryId" class="form-control">
                            @foreach (var item in ViewBag.OrganizationList)
                            {
                                <option value="@item.OrgId">@item.Name</option>
                            }
                        </select>
                    </div> *@
                    @* @Html.DropDownList("orgName", getOrgList(), "-- Select --", new { @class = "form-control show-tick", @id = "orgName", @required = "required" }) *@
                    @* <div class="form-group">
                        <label for="orgName">Select Organization</label>
                        @Html.DropDownListFor(model=>model.OrgId, getOrgList(), "-- Select --", new { @class = "form-control show-tick", @id = "orgName" })
                    </div> *@


                    <div class="form-group">
                        <label class="form-control-label">Organization Name</label>
                        <input asp-for="OrgName" placeholder="Enter your organization name" class="form-control" />
                        <span asp-validation-for="OrgName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Organization Address</label>
                        <input asp-for="OrgAddress" placeholder="Enter your organization address" class="form-control" />
                        <span asp-validation-for="OrgAddress" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Organization Contact</label>
                        <input asp-for="OrgContact" class="form-control" />
                        <span asp-validation-for="OrgContact" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Organization Email</label>
                        <input asp-for="OrgEmail" class="form-control" />
                        <span asp-validation-for="OrgEmail" class="text-danger"></span>
                    </div>

                    <div class="form-group row ">
                        <label class="form-control-label">Image</label>
                        <div class="col-sm-6">
                            <input type="file" name="file" />
                        </div>
                    </div>


                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>

                </div>
            </div>
        </form>
    </div>
</div>


@* <h1>Create</h1>

<h4>OrganizationViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="OrgName" class="control-label"></label>
                <input asp-for="OrgName" class="form-control" />
                <span asp-validation-for="OrgName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrgAddress" class="control-label"></label>
                <input asp-for="OrgAddress" class="form-control" />
                <span asp-validation-for="OrgAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrgContact" class="control-label"></label>
                <input asp-for="OrgContact" class="form-control" />
                <span asp-validation-for="OrgContact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrgEmail" class="control-label"></label>
                <input asp-for="OrgEmail" class="form-control" />
                <span asp-validation-for="OrgEmail" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>  *@

@* @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
 *@

NepalJobPortal/Views/Organization/Edit.cshtml
@model NepalJobPortal.Models.OrganizationViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Organization</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">Organization</a></li>
                            <li><a href="@Url.Action("Index","Organization")">List</a></li>
                            <li class="active">Edit</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-9">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div class="card">
                <div class="card-header"><strong>Update Organization</strong></div>
                <div class="card-body card-block">
                    <input asp-for="OrgId" class="form-control" hidden="hidden"/>
                    <div class="form-group">
                        <label class="form-control-label">Organization Name</label>
                        <input asp-for="OrgName" placeholder="Enter your organization name" class="form-control" />
                        <span asp-validation-for="OrgName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Organization Address</label>
                        <input asp-for="OrgAddress" placeholder="Enter your organization address" class="form-control" />
                        <span asp-validation-for="OrgAddress" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Organization Contact</label>
                        <input asp-for="OrgContact" class="form-control" />
                        <span asp-validation-for="OrgContact" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Organization Email</label>
                        <input asp-for="OrgEmail" class="form-control" />
                        <span asp-validation-for="OrgEmail" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Image </label>
                        <div class="col-sm-6">
                            @if (Model.OrgImage != null)
                            {
                                <img src="@Model.OrgImage.Replace(" ~", "")" width="100px" height="100px">
                            }
                            <input type="file" name="file" />
                        </div>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-primary" />
                    </div>

                </div>
            </div>
        </form>
    </div>
</div>






@* @model NepalJobPortal.Models.OrganizationViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>OrganizationViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OrgId" class="control-label"></label>
                <input asp-for="OrgId" class="form-control" />
                <span asp-validation-for="OrgId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrgName" class="control-label"></label>
                <input asp-for="OrgName" class="form-control" />
                <span asp-validation-for="OrgName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrgAddress" class="control-label"></label>
                <input asp-for="OrgAddress" class="form-control" />
                <span asp-validation-for="OrgAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrgContact" class="control-label"></label>
                <input asp-for="OrgContact" class="form-control" />
                <span asp-validation-for="OrgContact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrgEmail" class="control-label"></label>
                <input asp-for="OrgEmail" class="form-control" />
                <span asp-validation-for="OrgEmail" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Status" /> @Html.DisplayNameFor(model => model.Status)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedBy" class="control-label"></label>
                <input asp-for="UpdatedBy" class="form-control" />
                <span asp-validation-for="UpdatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedDate" class="control-label"></label>
                <input asp-for="UpdatedDate" class="form-control" />
                <span asp-validation-for="UpdatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeletedBy" class="control-label"></label>
                <input asp-for="DeletedBy" class="form-control" />
                <span asp-validation-for="DeletedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeletedDate" class="control-label"></label>
                <input asp-for="DeletedDate" class="form-control" />
                <span asp-validation-for="DeletedDate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
 *@

NepalJobPortal/Views/Organization/Index.cshtml
@model NepalJobPortal.Models.OrganizationViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    int i = 1;
}

<link rel="stylesheet" href="~/dashboardcontent/css/lib/datatable/dataTables.bootstrap.min.css">
<script src="~/dashboardcontent/js/lib/data-table/datatables.min.js"></script>
<script src="~/dashboardcontent/js/lib/data-table/dataTables.bootstrap.min.js"></script>

@* <p>
    <a asp-action="Create">Create New</a>
</p> *@

<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1><a asp-action="Create">Create New</a></h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">Organization</a></li>
                            <li class="active">List</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Organization List</strong>
            </div>
            <div class="card-body">
                <table id="bootstrap-data-table" class="table table-striped table-bordered" ">
                    <thead>
                        <tr>
                            <th>S.No</th>
                            <th>
                @Html.DisplayNameFor(model => model.OrgName)
                            </th>
                            <th>
                @Html.DisplayNameFor(model => model.OrgAddress)
                            </th>
                            <th>
                @Html.DisplayNameFor(model => model.OrgContact)
                            </th>
                            <th>
                @Html.DisplayNameFor(model => model.OrgEmail)
                            </th>
                            <th>Logo</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                @foreach (var item in Model.OrganizationList)
                {
                            <tr>
                                <td>@i</td>
                                <td>
                            @Html.DisplayFor(modelItem => item.OrgName)
                                </td>
                                <td>
                            @Html.DisplayFor(modelItem => item.OrgAddress)
                                </td>
                                <td>
                            @Html.DisplayFor(modelItem => item.OrgContact)
                                </td>
                                <td>
                            @Html.DisplayFor(modelItem => item.OrgEmail)
                                </td>
                                <td>
                                    <img src="@item.OrgImage.Replace(" ~", "")" width="100px" height="100px">
                                </td>
                                <td>
                            @Html.ActionLink("Edit", "Edit", new { id=item.OrgId }) |
                            @* @Html.ActionLink("Details", "Details", new { id=item.OrgId }) | *@
                            @Html.ActionLink("Delete", "Delete", new { id=item.OrgId })
                                </td>
                            </tr>
                    i++;
                }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        $('#bootstrap-data-table').DataTable();
    });
</script>