NepalJobPortal/Models/JobDescriptionViewModel.cs
namespace NepalJobPortal.Models
{
    public class JobDescriptionViewModel : CommonViewModel
    {
        public int? JobDescriptionId { get; set; }
        public int vendorOrgId { get; set; }
        public int CategoryId { get; set; }
        public string JobType { get; set; }
        public string Level { get; set; }
        public int VacancyNo { get; set; }
        public string EmployeeType { get; set; }
        public string JobLocation { get; set; }
        public string OfferedSalary { get; set; }
        public DateTime DeadLine { get; set; }
        public string EducationLevel { get; set; }
        public string ExperienceRequired { get; set; }
        public string OtherSpecification { get; set; }
        public string JobWorkDescription { get; set; }
        public string? VendorName {  get; set; }
        public string? CategoryName { get; set; }
        public string? VendorImage { get; set; }

        public List<JobDescriptionViewModel> JobDescriptionList { get; set; }

        public JobDescriptionViewModel()
        {
            JobDescriptionList = new List<JobDescriptionViewModel>();
        }
    }
}

NepalJobPortal/Controllers/JobDescriptionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NepalJobPortal.Data;
using NepalJobPortal.EntityModel;
using NepalJobPortal.Models;
using NepalJobPortal.Utilities;
using System.Security.Claims;

namespace NepalJobPortal.Controllers
{
    [Authorize]
    public class JobDescriptionController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;
        public JobDescriptionController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }
        public IActionResult Index()
        {
            JobDescriptionViewModel model = new JobDescriptionViewModel();
            model.JobDescriptionList = (from i in _applicationDbContext.JobDescription
                                        join j in _applicationDbContext.Category on i.CategoryId equals j.CategoryId
                                        join k in _applicationDbContext.VendorOrganization on i.vendorOrgId equals k.VendorOrgId
                                        where i.IsDeleted == false
                                        select new JobDescriptionViewModel
                                        {
                                            JobDescriptionId = i.JobDescriptionId,
                                            vendorOrgId = i.vendorOrgId,
                                            CategoryId = i.CategoryId,
                                            JobType = i.JobType,
                                            Level = i.Level,
                                            VacancyNo = i.VacancyNo,
                                            EmployeeType = i.EmployeeType,
                                            JobLocation = i.JobLocation,
                                            OfferedSalary = i.OfferedSalary,
                                            DeadLine = i.DeadLine,
                                            EducationLevel = i.EducationLevel,
                                            ExperienceRequired = i.ExperienceRequired,
                                            OtherSpecification = i.OtherSpecification,
                                            JobWorkDescription = i.JobWorkDescription,
                                            VendorName = k.VendorOrgName,
                                            CategoryName = j.CategoryName,
                                            VendorImage = k.VendorOrgImage,
                                        }).ToList();
            if(User.IsInRole("Vendor"))
            {
                var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var OrdId = _applicationDbContext.Users.Where(x => x.Id == currentUserId).Select(x => x.OrgId).FirstOrDefault();
                model.JobDescriptionList = model.JobDescriptionList
                    .Where(x => x.vendorOrgId == OrdId).ToList();
            }
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(JobDescriptionViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            int currentloginOrgId = CommonUtilities.GetCurrentUserId(_applicationDbContext, User.FindFirstValue(ClaimTypes.NameIdentifier));

            JobDescription org = new JobDescription();
            if(User.IsInRole("SuperAdmin"))
            {
                org.vendorOrgId = model.vendorOrgId;
            }
            else
            {
                org.vendorOrgId = currentloginOrgId;
            }
            org.CategoryId = model.CategoryId;
            org.JobType = model.JobType;
            org.Level = model.Level;
            org.VacancyNo = model.VacancyNo;
            org.EmployeeType = model.EmployeeType;
            org.JobLocation = model.JobLocation;
            org.OfferedSalary = model.OfferedSalary;
            org.DeadLine = model.DeadLine;
            org.EducationLevel = model.EducationLevel;
            org.ExperienceRequired = model.ExperienceRequired;
            org.OtherSpecification = model.OtherSpecification;
            org.JobWorkDescription = model.JobWorkDescription;
            org.Status = true;
            org.CreatedBy = currentloginOrgId;
            org.CreatedDate = DateTime.Now;
            _applicationDbContext.Entry(org).State = EntityState.Added;
            _applicationDbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            JobDescriptionViewModel model = new JobDescriptionViewModel();
            if (id > 0)
            {
                var org = _applicationDbContext.JobDescription.Where(x => x.JobDescriptionId == id).FirstOrDefault();
                if (org != null)
                {
                    model.JobDescriptionId = org.JobDescriptionId;
                    model.vendorOrgId = org.vendorOrgId;
                    model.CategoryId = org.CategoryId;
                    model.JobType = org.JobType;
                    model.Level = org.Level;
                    model.VacancyNo = org.VacancyNo;
                    model.EmployeeType = org.EmployeeType;
                    model.JobLocation = org.JobLocation;
                    model.OfferedSalary = org.OfferedSalary;
                    model.DeadLine = org.DeadLine;
                    model.EducationLevel = org.EducationLevel;
                    model.ExperienceRequired = org.ExperienceRequired;
                    model.OtherSpecification = org.OtherSpecification;
                    model.JobWorkDescription = org.JobWorkDescription;
                }
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(JobDescriptionViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            int currentloginOrgId = CommonUtilities.GetCurrentUserId(_applicationDbContext, User.FindFirstValue(ClaimTypes.NameIdentifier));

            JobDescription org = new JobDescription();
            org.JobDescriptionId = model.JobDescriptionId??0;
            org.vendorOrgId = model.vendorOrgId;
            org.CategoryId = model.CategoryId;
            org.JobType = model.JobType;
            org.Level = model.Level;
            org.VacancyNo = model.VacancyNo;
            org.EmployeeType = model.EmployeeType;
            org.JobLocation = model.JobLocation;
            org.OfferedSalary = model.OfferedSalary;
            org.DeadLine = model.DeadLine;
            org.EducationLevel = model.EducationLevel;
            org.ExperienceRequired = model.ExperienceRequired;
            org.OtherSpecification = model.OtherSpecification;
            org.JobWorkDescription = model.JobWorkDescription;
            org.Status = true;
            org.UpdatedBy = currentloginOrgId;
            org.UpdatedDate = DateTime.Now;
            _applicationDbContext.Entry(org).State = EntityState.Modified;
            _applicationDbContext.Entry(org).Property(x => x.CreatedBy).IsModified = false;
            _applicationDbContext.Entry(org).Property(x => x.CreatedDate).IsModified = false;
            _applicationDbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            if (id > 0)
            {
                int currentloginOrgId = CommonUtilities.GetCurrentUserId(_applicationDbContext, User.FindFirstValue(ClaimTypes.NameIdentifier));

                var org = _applicationDbContext.JobDescription.Where(x => x.JobDescriptionId == id).FirstOrDefault();
                if (org != null)
                {
                    org.DeletedBy = currentloginOrgId;
                    org.DeletedDate = DateTime.Now;
                    org.IsDeleted = true;
                    _applicationDbContext.Entry(org).State = EntityState.Modified;
                    _applicationDbContext.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            JobDescriptionViewModel model = new JobDescriptionViewModel();
            model.JobDescriptionList = (from i in _applicationDbContext.JobDescription
                                        join j in _applicationDbContext.Category on i.CategoryId equals j.CategoryId
                                        join k in _applicationDbContext.VendorOrganization on i.vendorOrgId equals k.VendorOrgId
                                        where i.IsDeleted == false && i.JobDescriptionId == id
                                        select new JobDescriptionViewModel
                                        {
                                            JobDescriptionId = i.JobDescriptionId,
                                            vendorOrgId = i.vendorOrgId,
                                            CategoryId = i.CategoryId,
                                            JobType = i.JobType,
                                            Level = i.Level,
                                            VacancyNo = i.VacancyNo,
                                            EmployeeType = i.EmployeeType,
                                            JobLocation = i.JobLocation,
                                            OfferedSalary = i.OfferedSalary,
                                            DeadLine = i.DeadLine,
                                            EducationLevel = i.EducationLevel,
                                            ExperienceRequired = i.ExperienceRequired,
                                            OtherSpecification = i.OtherSpecification,

NepalJobPortal/Views/JobDescription/Create.cshtml
@model NepalJobPortal.Models.JobDescriptionViewModel

@* @using Microsoft.Extensions.DependencyInjection *@
@inject IServiceProvider ServiceProvider
@using NepalJobPortal.Utilities;

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

    Func<IEnumerable<SelectListItem>> getVendorList = () => CommonUtilities.GetVendorList(ServiceProvider);
    Func<IEnumerable<SelectListItem>> getCategoryList = () => CommonUtilities.GetCategoryList(ServiceProvider);
}

<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Job List</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">Job</a></li>
                            <li><a href="@Url.Action("Index","JobDescription")">List</a></li>
                            <li class="active">Create</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-9">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="card">
                <div class="card-header"><strong>Create Job List</strong></div>
                <div class="card-body card-block">
                   
                    @if(User.IsInRole("SuperAdmin"))
                    {
                        <div class="form-group">
                            <label for="orgName">Select Vendor</label>
                            @Html.DropDownListFor(model=>model.vendorOrgId, getVendorList(), "-- Select --", new { @class = "form-control show-tick", @id = "orgName" })
                        </div>
                    }
                    
                    <div class="form-group">
                        <label for="orgName">Select Category</label>
                        @Html.DropDownListFor(model=>model.CategoryId, getCategoryList(), "-- Select --", new { @class = "form-control show-tick", @id = "orgName" })
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Job Type</label>
                        <input asp-for="JobType" class="form-control" />
                        <span asp-validation-for="JobType" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Level</label>
                        <input asp-for="Level" class="form-control" />
                        <span asp-validation-for="Level" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Vacancy No</label>
                        <input asp-for="VacancyNo" class="form-control" />
                        <span asp-validation-for="VacancyNo" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Employee Type</label>
                        <input asp-for="EmployeeType" class="form-control" />
                        <span asp-validation-for="EmployeeType" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Job Location</label>
                        <input asp-for="JobLocation" class="form-control" />
                        <span asp-validation-for="JobLocation" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Offered Salary</label>
                        <input asp-for="OfferedSalary" class="form-control" />
                        <span asp-validation-for="OfferedSalary" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">DeadLine</label>
                        <input asp-for="DeadLine" class="form-control" />
                        <span asp-validation-for="DeadLine" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">Education Level</label>
                        <input asp-for="EducationLevel" class="form-control" />
                        <span asp-validation-for="EducationLevel" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Experience Required</label>
                        <input asp-for="ExperienceRequired" class="form-control" />
                        <span asp-validation-for="ExperienceRequired" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">Other Specification</label>
                        <textarea asp-for="OtherSpecification" class="form-control"></textarea>
                        <span asp-validation-for="OtherSpecification" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">JobWork Description</label>
                        <textarea asp-for="JobWorkDescription" class="form-control"></textarea>
                        <span asp-validation-for="JobWorkDescription" class="text-danger"></span>
                    </div>
                   
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>

                </div>
            </div>
        </form>
    </div>
</div>

NepalJobPortal/Views/JobDescription/Details.cshtml
@model NepalJobPortal.Models.JobDescriptionViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Job Detail</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">Job</a></li>
                            <li><a href="@Url.Action("Index","JobDescription")">List</a></li>
                            <li class="active">Details</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row">
    @foreach(var item in Model.JobDescriptionList)
    {
        <div class="col-lg-12 col-md-12 col-sm-12">
            VendorName : @item.VendorName
        </div>
        
        <div class="col-lg-12 col-md-12 col-sm-12">
            CategoryName : @item.CategoryName
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            JobType : @item.JobType
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            Level : @item.Level
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            VacancyNo : @item.VacancyNo
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            EmployeeType : @item.EmployeeType
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            JobLocation : @item.JobLocation
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            OfferedSalary : @item.OfferedSalary
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            DeadLine : @item.DeadLine
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            EducationLevel : @item.EducationLevel
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            ExperienceRequired : @item.ExperienceRequired
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            OtherSpecification : @item.OtherSpecification
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            JobWorkDescription : @item.JobWorkDescription
        </div>
    }
</div>

NepalJobPortal/Views/JobDescription/Edit.cshtml
@model NepalJobPortal.Models.JobDescriptionViewModel
@inject IServiceProvider ServiceProvider
@using NepalJobPortal.Utilities;
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    Func<IEnumerable<SelectListItem>> getVendorList = () => CommonUtilities.GetVendorList(ServiceProvider);
    Func<IEnumerable<SelectListItem>> getCategoryList = () => CommonUtilities.GetCategoryList(ServiceProvider);

}

<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Job List</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">Job</a></li>
                            <li><a href="@Url.Action("Index","JobDescription")">List</a></li>
                            <li class="active">Edit</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-9">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div class="card">
                <div class="card-header"><strong>Update Job List</strong></div>
                <div class="card-body card-block">
                    <input asp-for="JobDescriptionId" class="form-control" hidden="hidden" />
                    @if (User.IsInRole("SuperAdmin"))
                    {
                        <div class="form-group">
                            <label for="orgName">Select Vendor</label>
                            @Html.DropDownListFor(model=>model.vendorOrgId, getVendorList(), "-- Select --", new { @class = "form-control show-tick", @id = "orgName" })
                        </div>
                    }
                    else
                    {
                        <input asp-for="vendorOrgId" class="form-control" hidden="hidden" />
                    }

                    <div class="form-group">
                        <label for="orgName">Select Category</label>
                        @Html.DropDownListFor(model=>model.CategoryId, getCategoryList(), "-- Select --", new { @class = "form-control show-tick", @id = "orgName" })
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Job Type</label>
                        <input asp-for="JobType" class="form-control" />
                        <span asp-validation-for="JobType" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Level</label>
                        <input asp-for="Level" class="form-control" />
                        <span asp-validation-for="Level" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Vacancy No</label>
                        <input asp-for="VacancyNo" class="form-control" />
                        <span asp-validation-for="VacancyNo" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Employee Type</label>
                        <input asp-for="EmployeeType" class="form-control" />
                        <span asp-validation-for="EmployeeType" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Job Location</label>
                        <input asp-for="JobLocation" class="form-control" />
                        <span asp-validation-for="JobLocation" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Offered Salary</label>
                        <input asp-for="OfferedSalary" class="form-control" />
                        <span asp-validation-for="OfferedSalary" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">DeadLine</label>
                        <input asp-for="DeadLine" class="form-control" />
                        <span asp-validation-for="DeadLine" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">Education Level</label>
                        <input asp-for="EducationLevel" class="form-control" />
                        <span asp-validation-for="EducationLevel" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">Experience Required</label>
                        <input asp-for="ExperienceRequired" class="form-control" />
                        <span asp-validation-for="ExperienceRequired" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label">Other Specification</label>
                        <textarea asp-for="OtherSpecification" class="form-control"></textarea>
                        <span asp-validation-for="OtherSpecification" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label">JobWork Description</label>
                        <textarea asp-for="JobWorkDescription" class="form-control"></textarea>
                        <span asp-validation-for="JobWorkDescription" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-primary" />
                    </div>

                </div>
            </div>
        </form>
    </div>
</div>

NepalJobPortal/Views/JobDescription/Index.cshtml
@model NepalJobPortal.Models.JobDescriptionViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    int i = 1;
}

<link rel="stylesheet" href="~/dashboardcontent/css/lib/datatable/dataTables.bootstrap.min.css">
<script src="~/dashboardcontent/js/lib/data-table/datatables.min.js"></script>
<script src="~/dashboardcontent/js/lib/data-table/dataTables.bootstrap.min.js"></script>


<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1><a asp-action="Create">Create New</a></h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">JObDescription</a></li>
                            <li class="active">List</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Job List</strong>
            </div>
            <div class="card-body">
                <table id="bootstrap-data-table" class="table table-striped table-bordered" ">
                    <thead>
                        <tr>
                            <th>S.No</th>
                            <th>
                @Html.DisplayNameFor(model => model.VendorName)
                            </th>
                            <th>
                @Html.DisplayNameFor(model => model.CategoryName)
                            </th>
                            <th>
                @Html.DisplayNameFor(model => model.JobType)
                            </th>
                            <th>
                @Html.DisplayNameFor(model => model.Level)
                            </th>
                            <th>
                @Html.DisplayNameFor(model => model.VacancyNo)
                            </th>
                            <th>
                @Html.DisplayNameFor(model => model.EmployeeType)
                            </th>
                            <th>
                @Html.DisplayNameFor(model => model.DeadLine)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                @foreach (var item in Model.JobDescriptionList)
                {
                            <tr>
                                <td>@i</td>
                                <td>
                            @Html.DisplayFor(modelItem => item.VendorName)
                                </td>
                                <td>
                            @Html.DisplayFor(modelItem => item.CategoryName)
                                </td>
                                <td>
                            @Html.DisplayFor(modelItem => item.JobType)
                                </td>
                                <td>
                            @Html.DisplayFor(modelItem => item.Level)
                                </td>
                                <td>
                            @Html.DisplayFor(modelItem => item.VacancyNo)
                                </td>
                                <td>
                            @Html.DisplayFor(modelItem => item.EmployeeType)
                                </td>
                                <td>
                            @Html.DisplayFor(modelItem => item.DeadLine)
                                </td>
                                <td>
                            @Html.ActionLink("Edit", "Edit", new { id=item.JobDescriptionId }) |
                            @Html.ActionLink("Details", "Details", new { id=item.JobDescriptionId }) |
                            @Html.ActionLink("Delete", "Delete", new { id=item.JobDescriptionId })
                                </td>
                            </tr>
                    i++;
                }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        $('#bootstrap-data-table').DataTable();
    });
</script>